### ISSUE TITLE
Relies on launch shell having nodejs in PATH

### ISSUE THREAD

**Issue by dignifiedquire** [jbenet/node-subcomandante#1]
From IRC

> dignifiedquire:
> daviddias: whyrusleeping jbenet any of you guys have an idea how this error could be generated https://gist.github.com/Dignifiedquire/9bde0097eb05e4cb8c8f (yes the files in question exist I checked that)
> [12:01am] whyrusleeping:
> dignifiedquire: how did you repro that?
> [12:01am] daviddias:
> how does that happen?
> [12:01am] whyrusleeping:
> looks like nodejs stuff
> [12:01am] whyrusleeping:
> node.js.js
> [12:01am] dignifiedquire:
> it only happens when I package the electron app
> [12:02am] whyrusleeping:
> you have node installed?
> [12:02am] dignifiedquire:
> it doesn’t happen without 
> [12:02am] Encrypt left the chat room. (Quit: Sleeping time!)
> [12:02am] dignifiedquire:
> only if you use the right shell
> [12:02am] dignifiedquire:
> (zsh + nvm)
> [12:04am] dignifiedquire:
> so you think the issue is that the subcom file doesn’t find the node binary?
> [12:07am] dignifiedquire:
> makes sense, now that I reread the error message -.-
> [12:10am] noffle:
> whyrusleeping: alas!
> [12:10am] dignifiedquire:
> it seems to me that this is an issue in subcomandante, as it shouldn’t rely on the shell having node linked

It seems the culprit is relying on the hash bang [here](https://github.com/jbenet/node-subcomandante/blob/master/subcom#L1) as that will only work if the enclosing shell does have nodejs in `PATH`, which we can not guarantee when packaging it as a native app as far as I understand.

**Comment by daviddias** [comment]
> 16:20 <+daviddias> dignifiedquire was trying to get it working simply by removing that line
> 16:20 <+daviddias> it fired up the node
> 16:21 <+daviddias> we shouldn't have to specify that in the file since it is always run in the node context

**Comment by jbenet** [comment]
The point of subcom binary is that it needs to run as a separate process. We need to find a way to execute it with node without expecting the standard toolchain to be there.

Can we expect `node` to be there?

**Comment by jbenet** [comment]
we could remove that line, and then exec it with node directly, by finding where the current node binary from the parent context is located.

**Comment by dignifiedquire** [comment]
> we could remove that line, and then exec it with node directly, by finding where the current node binary from the parent context is located.

Agreed

> Can we expect node to be there?

You can only expect that the process executing the file has a node binary, but not that it is in the `PATH`.

**Comment by jbenet** [comment]
@Dignifiedquire is the actual binary guaranteed to be there and executable? or do we have to do something like fork?

**Comment by dignifiedquire** [comment]
I don't think there is a reliable way to find the path of the executable from inside the running process, so the safest way would be to use `child_process.fork` I guess.

**Comment by jbenet** [comment]
@Dignifiedquire isn't `process.argv[0]` the `node` path?

**Comment by dignifiedquire** [comment]
It looks like `process.argv[0]` should be supported everywhere, I've tested it with forked child processes on OS X and that still works, will check on windows now to be sure that it's available as expected there as well.

**Comment by dignifiedquire** [comment]
@jbenet windows checks out as well:

![screen shot 2015-10-12 at 09 42 24](https://cloud.githubusercontent.com/assets/790842/10423310/92aa79d6-70c5-11e5-856c-1fb351dc27cd.png)

**Comment by jbenet** [comment]
Ok great! let's do that

**Comment by jbenet** [comment]
Published as `1.0.4`

**Comment by jbenet** [comment]
thanks @Dignifiedquire

**Comment by dignifiedquire** [comment]
Thanks @jbenet for the quick fix, will test it later
