### ISSUE TITLE
Being unable to publish

### ISSUE THREAD

**Issue by daviddias** [jbenet/node-subcomandante#8]
Despite

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/1211152/39417466-4745ea38-4c4c-11e8-9a62-958ec707fd1c.png">

I'm getting
```
» npm publish
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "subcomandante". Are you logged in as the correct user? : subcomandante

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/imp/.npm/_logs/2018-04-30T06_57_52_361Z-debug.log
```

Contacted npm.

**Comment by daviddias** [comment]
Reply from npm

<img width="803" alt="image" src="https://user-images.githubusercontent.com/1211152/39469083-77faec40-4d2e-11e8-852b-37780e6b8d18.png">

This doesn't match what https://www.npmjs.com/package/subcomandante shows, but let's give it a shot. @travisperson can you check if you can indeed publish and/or give me permission?

**Comment by travisperson** [comment]
Interesting. It shows you as a collaborator, but you weren't showing up in the maintainer list. I was able to add you though, and publish the new version you had pushed to master.

https://www.npmjs.com/package/subcomandante/v/1.2.0

Looks like everything is in order now. Going to close this out, and will open a PR for https://github.com/ipfs/js-ipfsd-ctl to update the dependency there.
